broadway:
    event_store: Broadway\EventStore\Dbal\DBALEventStore

services:
    Broadway\EventStore\Dbal\DBALEventStore:
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@broadway.serializer.payload"
            - "@broadway.serializer.metadata"
            - "events"
            - false
            - "@broadway.uuid.converter"

    Broadway\EventStore\EventStore: '@Broadway\EventStore\Dbal\DBALEventStore'
    Broadway\EventHandling\EventBus: '@broadway.event_handling.event_bus'
