version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/research
    php:
        image: php:fpm
        build:
          context: php
        expose:
            - "9001"
        volumes:
            - ./:/var/www/research
        environment:
            PHP_IDE_CONFIG: serverName=PHPSERVERNAME
    db:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=wojtek
            - POSTGRES_PASSWORD=wojtek
            - POSTGRES_DB=messenger
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres-data:/var/lib/postgresql/data
